var annotated_dup =
[
    [ "parsing char* in constexpr", "md_README.html#autotoc_md1", null ],
    [ "evaluating simple expressions", "md_README.html#autotoc_md2", null ],
    [ "c", "structc.html", null ],
    [ "c_list", "structc__list.html", "structc__list" ],
    [ "div_", "structdiv__.html", null ],
    [ "double_quote", "structdouble__quote.html", null ],
    [ "integer", "structinteger.html", "structinteger" ],
    [ "is_templated_int_collection", "structis__templated__int__collection.html", null ],
    [ "is_templated_int_collection< Type< Args... >, Type >", "structis__templated__int__collection_3_01Type_3_01Args_8_8_8_01_4_00_01Type_01_4.html", null ],
    [ "list", "structlist.html", "structlist" ],
    [ "list_end", "structlist__end.html", null ],
    [ "list_start", "structlist__start.html", null ],
    [ "minus", "structminus.html", null ],
    [ "mul", "structmul.html", null ],
    [ "non_character", "structnon__character.html", null ],
    [ "non_integer", "structnon__integer.html", null ],
    [ "plus", "structplus.html", null ],
    [ "quote", "structquote.html", null ],
    [ "special_character", "structspecial__character.html", null ],
    [ "term", "structterm.html", null ],
    [ "token_list", "structtoken__list.html", "structtoken__list" ],
    [ "whitespace", "structwhitespace.html", null ]
];